/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2021-05-12 05:35:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>폴인사이트</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.11.3.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,width=device-width\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\" />\r\n");
      out.write("<link rel=\"icon\" href=\"img/favi.png\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"roll\"></div>\r\n");
      out.write("\t<div id=\"quickmw\">\r\n");
      out.write("\t\t<div id=\"quickm\">\r\n");
      out.write("\t\t\t<div class=\"qms\">\r\n");
      out.write("\t\t\t\t<img id=\"icon1\" src=\"img/icon1.png\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='request.php';\" />\r\n");
      out.write("\t\t\t\t<div class=\"qmd1\" onclick=\"location.href='request.php';\">조사문의</div>\r\n");
      out.write("\t\t\t\t<div class=\"qmd2\" onclick=\"location.href='request.php';\">\r\n");
      out.write("\t\t\t\t\t궁금하신 조사에 대해<br>문의해 보세요.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"qms\">\r\n");
      out.write("\t\t\t\t<img id=\"icon2\" src=\"img/icon2.png\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='field.php';\" />\r\n");
      out.write("\t\t\t\t<div class=\"qmd1\" onclick=\"location.href='field.php';\">사업영역</div>\r\n");
      out.write("\t\t\t\t<div class=\"qmd2\" onclick=\"location.href='field.php';\">\r\n");
      out.write("\t\t\t\t\t과학적인 DATA분석으로 정책연구의<br>솔루션을 제공합니다.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"qms3\" class=\"qms\">\r\n");
      out.write("\t\t\t\t<img id=\"icon3\" src=\"img/icon3.png\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='onlinesurvey.php';\" />\r\n");
      out.write("\t\t\t\t<div class=\"qmd1\" onclick=\"location.href='onlinesurvey.php';\">온라인조사</div>\r\n");
      out.write("\t\t\t\t<div class=\"qmd2\" onclick=\"location.href='onlinesurvey.php';\">\r\n");
      out.write("\t\t\t\t\t폴인사이트에서 진행하는<br>각종 조사에 참여하고 싶다면?\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"bm\">\r\n");
      out.write("\t\t<div class=\"bmd\">\r\n");
      out.write("\t\t\t<div class=\"bmdt\">이슈리포트</div>\r\n");
      out.write("\t\t\t<div id=\"bmdid1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bmd\">\r\n");
      out.write("\t\t\t<div class=\"bmdt\">트렌드맞춤형 마케팅</div>\r\n");
      out.write("\t\t\t<div id=\"bmdid2\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bmd\">\r\n");
      out.write("\t\t\t<div class=\"bmdt\">공지사항</div>\r\n");
      out.write("\t\t\t<div id=\"bmdid3\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t[62265] 광주광역시 광산구 첨단내촌로 70번길 55(월계동 769-4) 404호<br>T :\r\n");
      out.write("\t\t062-374-7011 F : 062-374-7013 E : polinsight@gmail.com<br> <br>COPYRIGHT(C)\r\n");
      out.write("\t\t2019 POLINSIGHT. ALL RIGHTS RESERVED\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tdocument.getElementById(\"roll\").innerHTML = \"<div id='slidebtn'><div id='leftbtn' onclick='slideleft();'></div><div id='rightbtn' onclick='slideright();'></div></div><div id='rid1'></div><img id='ri1' src='img/main4.jpg'/>\"\r\n");
      out.write("\t\t\t+ \"<div id='topd1'><div class='topd1d'>WEB&DESIGN</div><div class='topd2d'><span class='topd2s'>웹&디자인</span></div><div class='topd4d'>빠르게 변화하는 <span class='topd4s'>트렌드맞춤형 마케팅</span> 시스템</div></div>\"\r\n");
      out.write("\t\t\t+ \"<div id='rid2'></div><img id='ri2' src='img/main1.jpg'/>\"\r\n");
      out.write("\t\t\t+ \"<div id='topd2'><div class='topd1d'>POLL</div><div class='topd2d'><span class='topd2s'>여론조사</span></div><div class='topd4d'>믿을만한 <span class='topd4s'>여론 동향 파악</span> 및 <span class='topd4s'>솔루션 제공</span></div></div>\"\r\n");
      out.write("\t\t\t+ \"<div id='rid3'></div><img id='ri3' src='img/main2.jpg'/>\"\r\n");
      out.write("\t\t\t+ \"<div id='topd3'><div class='topd1d'>PUBLIC DATA</div><div class='topd2d'><span class='topd2s'>공공데이터분석</span></div><div class='topd4d'><span class='topd4s'>GIS, 네트워크분석</span>을 활용한 <span class='topd4s'>데이터 시각화</span></div></div>\"\r\n");
      out.write("\t\t\t+ \"<div id='rid4'></div><img id='ri4' src='img/main3.jpg'/>\"\r\n");
      out.write("\t\t\t+ \"<div id='topd4'><div class='topd1d'>POLITICS</div><div class='topd2d'><span class='topd2s'>정책연구</span></div><div class='topd4d'><span class='topd4s'>데이터</span>에 기반한 <span class='topd4s'>인사이트 도출</span></div></div>\";\r\n");
      out.write("\tdocument.getElementById(\"leftbtn\").innerHTML = \"<img id='lbi' src='img/icon_arrowl.png'/>\";\r\n");
      out.write("\tdocument.getElementById(\"rightbtn\").innerHTML = \"<img id='rbi' src='img/icon_arrowr.png'/>\";\r\n");
      out.write("\t//var rollleft = $(\"#roll\").offset().left - 1000;\r\n");
      out.write("\t//var rollleft2 = $(\"#roll\").offset().left + 150;\r\n");
      out.write("\t//var rollleft3 = $(\"#roll\").offset().left;\r\n");
      out.write("\t//var rollright = $(\"#roll\").offset().left + 1000;\r\n");
      out.write("\t//var rollright2 = $(\"#roll\").offset().left + 2000;\r\n");
      out.write("\t//var rolldleft = $(\"#roll\").offset().left - 850;\r\n");
      out.write("\t//var rolldright = $(\"#roll\").offset().left + 1150;\r\n");
      out.write("\t//var rolldright2 = $(\"#roll\").offset().left + 2150;\r\n");
      out.write("\t//var roll1 = $(\"#roll\").offset().left + 25;\r\n");
      out.write("\t//var roll2 = $(\"#roll\").offset().left + 980;\r\n");
      out.write("\t//$(\"#ri1\").offset({\r\n");
      out.write("\t//\tleft : rollleft\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#rid1\").offset({\r\n");
      out.write("\t//\tleft : rollleft\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#ri3\").offset({\r\n");
      out.write("\t//\tleft : rollright\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#rid3\").offset({\r\n");
      out.write("\t//\tleft : rollright\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#ri4\").offset({\r\n");
      out.write("\t//\tleft : rollright2\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#rid4\").offset({\r\n");
      out.write("\t//\tleft : rollright2\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#topd1\").offset({\r\n");
      out.write("\t//\tleft : rolldleft\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#topd2\").offset({\r\n");
      out.write("\t//\tleft : rollleft2\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#rid2\").offset({\r\n");
      out.write("\t//\tleft : rollleft3\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#topd3\").offset({\r\n");
      out.write("\t//\tleft : rolldright\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#topd4\").offset({\r\n");
      out.write("\t//\tleft : rolldright2\r\n");
      out.write("\t//});\r\n");
      out.write("\t//$(\"#slidebtn\").offset({\r\n");
      out.write("\t//\tleft : roll1\r\n");
      out.write("\t//});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
