/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2021-05-13 13:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.FileReader;
import java.io.BufferedReader;

public final class makeForm2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.FileReader");
    _jspx_imports_classes.add("java.io.BufferedReader");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>관리자 페이지</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/form.css\">\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("\tbackground:#4CAF50;\n");
      out.write("}\n");
      out.write(".form{\n");
      out.write("\tbackground:#FFFFFF;\n");
      out.write("\tmax-width:600px;\n");
      out.write("\tmargin: 10px auto 10px;\n");
      out.write("\tpadding: 45px;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tbox-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\n");
      out.write("}\n");
      out.write(".container{\n");
      out.write("\tmargin-top: 50px;\n");
      out.write("}\n");
      out.write("h3{\n");
      out.write("\tfont-size:20px;\n");
      out.write("}\n");
      out.write("div.form{\n");
      out.write("\ttext-align:center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\t\t\t\t\n");
      out.write("\t<h3 style=\"text-align: center;\">설문 항목 추가</h3>\n");
      out.write("\t\t<div class=\"form\" style=\"padding-top: 20px;\">\n");
      out.write("\t\t\t<form id=\"form\" method=\"post\" action=\"formPro.jsp\">\n");
      out.write("\t\t\t\t<div class=\"questions\" id=\"questions\"></div>\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"form\" value=\"");
      out.print(request.getParameter("form_id"));
      out.write("\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"num_of_question\" value=\"0\">\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"num_of_index\" value=\"0\">\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn_addQuestion\" value=\"새 질문\" onClick=\"addQuestion()\">\n");
      out.write("\t\t\t\t<button class=\"form_submit\" onclick=\"formSubmit()\">완료</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\tvar questionIndex = 0;\n");
      out.write("\t\tvar indexArray = [];\n");
      out.write("\t\tvar click = true;\n");
      out.write("\t\t\n");
      out.write("\t\tfunction addOption(q_idx) {\n");
      out.write("\t\t\tlet table = document.getElementById(\"option\" + q_idx);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet counter = document.getElementById(\"option_count\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet rowlen = table.rows.length + 1;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif (rowlen > 7) {\n");
      out.write("\t\t\t\talert(\"최대 7개 항목을 입력하실 수 있습니다.\");\n");
      out.write("\t\t\t\treturn 0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// var row = table.insertRow(); // IE와 Chrome 동작을 달리함.\n");
      out.write("\t\t\tlet row = table.insertRow(rowlen - 1); // HTML에서의 권장 표준 문법\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet newcell = row.insertCell(0);\n");
      out.write("\t\t\tnewcell.innerHTML = \"O\";\n");
      out.write("\t\t\tnewcell.className = \"blank\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tnewcell = row.insertCell(1);\n");
      out.write("\t\t\tnewcell.innerHTML = \"<input type='text' class='option_content' placeholder='항목' name='option\" + q_idx + \"_\" + (rowlen - 1) + \"'>\";\n");
      out.write("\t\t\tnewcell.className = \"option\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tnewcell = row.insertCell(2);\n");
      out.write("\t\t\tnewcell.innerHTML = \"<input type='button' class='create_delete_option' onClick='addOption(\" + q_idx + \")' value='+'>\"\n");
      out.write("\t\t\t+ \"<input type='button' class='create_delete_option' onClick='removeOption(\" + q_idx + \")' value='-'>\";\n");
      out.write("\t\t\tnewcell.className = \"create_delete_option\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tcounter.value = rowlen;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction removeOption(q_idx) {\n");
      out.write("\t\t\tlet table = document.getElementById(\"option\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet counter = document.getElementById(\"option_count\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet rowlen = table.rows.length - 1;\n");
      out.write("\n");
      out.write("\t\t\tif (rowlen < 1) {\n");
      out.write("\t\t\t\talert(\"1개 이상의 항목을 입력하셔야 합니다.\");\n");
      out.write("\t\t\t\treturn 0;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\ttable.deleteRow(rowlen);\n");
      out.write("\n");
      out.write("\t\t\tcounter.value = rowlen;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction addMatrixQuestion(q_idx) {\n");
      out.write("\t\t\tlet table = document.getElementById(\"question\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet counter = document.getElementById(\"question_count\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet rowlen = table.rows.length + 1;\n");
      out.write("\n");
      out.write("\t\t\tif (rowlen > 7) {\n");
      out.write("\t\t\t\talert(\"최대 7개 항목을 입력하실 수 있습니다.\");\n");
      out.write("\t\t\t\treturn 0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t// var row = table.insertRow(); // IE와 Chrome 동작을 달리함.\n");
      out.write("\t\t\tlet row = table.insertRow(rowlen - 1); // HTML에서의 권장 표준 문법\n");
      out.write("\n");
      out.write("\t\t\tlet newcell = row.insertCell(0);\n");
      out.write("\t\t\tnewcell.innerHTML = \"\";\n");
      out.write("\t\t\tnewcell.className = \"question_number\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tnewcell = row.insertCell(1);\n");
      out.write("\t\t\tnewcell.innerHTML = \"<input type='text' class='question_title' placeholder='질문을 입력하세요.' name='question_title\" + q_idx + \"_\" + (rowlen - 1) + \"'>\";\n");
      out.write("\t\t\tnewcell.className = \"question_title\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tnewcell = row.insertCell(2);\n");
      out.write("\t\t\tnewcell.innerHTML = \"<input type='button' class='create_delete_question' onClick='addMatrixQuestion(\" + q_idx + \")' value='+'>\"\n");
      out.write("\t\t\t+ \"<input type='button' class='create_delete_question' onClick='removeMatrixQuestion(\" + q_idx + \")' value='-'>\";\n");
      out.write("\t\t\tnewcell.className = \"create_delete_question\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tcounter.value = rowlen;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction removeMatrixQuestion(q_idx) {\n");
      out.write("\t\t\tlet table = document.getElementById(\"question\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet counter = document.getElementById(\"question_count\" + q_idx);\n");
      out.write("\n");
      out.write("\t\t\tlet rowlen = table.rows.length - 1;\n");
      out.write("\n");
      out.write("\t\t\tif (rowlen < 1) {\n");
      out.write("\t\t\t\talert(\"1개 이상의 항목을 입력하셔야 합니다.\");\n");
      out.write("\t\t\t\treturn 0;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\ttable.deleteRow(rowlen);\n");
      out.write("\n");
      out.write("\t\t\tcounter.value = rowlen;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction addQuestion() {\n");
      out.write("\t\t\tquestionIndex++;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tconst form = document.getElementById('form');\n");
      out.write("\n");
      out.write("\t\t\tform.num_of_question.value++;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet question = multiple(questionIndex);\n");
      out.write("\n");
      out.write("\t\t\tconst newQuestion = document.createElement('div');\n");
      out.write("\n");
      out.write("\t\t\tnewQuestion.innerHTML = question;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tquestions.appendChild(newQuestion);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tindexArray.push(questionIndex);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tquestionNumbering();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction removeQuestion() {\n");
      out.write("\t\t\tconst form = document.getElementById('form');\n");
      out.write("\n");
      out.write("\t\t\tlet question = document.activeElement.parentNode;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet index = question.querySelector(\"#questionIndex\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor(let i = 0; i < indexArray.length; i++) {\n");
      out.write("\t\t\t\tif(indexArray[i] == index.value)  {\n");
      out.write("\t\t\t\t\tindexArray.splice(i, 1);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tquestion.parentNode.removeChild(question);\n");
      out.write("\n");
      out.write("\t\t\tform.num_of_question.value--;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tquestionNumbering();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction changeType(questionIdx) {\n");
      out.write("\t\t\tlet sel = document.activeElement;\n");
      out.write("\n");
      out.write("\t\t\tlet type = sel.value;\n");
      out.write("\n");
      out.write("\t\t\tlet question = document.activeElement.parentNode.parentNode.parentNode;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet index = question.querySelector(\"#questionIndex\").value;\n");
      out.write("\n");
      out.write("\t\t\tswitch (type) {\n");
      out.write("\t\t\tcase \"multiple\":\n");
      out.write("\t\t\t\tquestion.innerHTML = multiple(index);\n");
      out.write("\t\t\t\tbreak;\n");
      out.write("\t\t\tcase \"shortanswer\":\n");
      out.write("\t\t\t\tquestion.innerHTML = shortanswer(index);\n");
      out.write("\t\t\t\tbreak;\n");
      out.write("\t\t\tcase \"matrix\":\n");
      out.write("\t\t\t\tquestion.innerHTML = matrix(index);\n");
      out.write("\t\t\t\tbreak;\n");
      out.write("\t\t\tdefault:\n");
      out.write("\t\t\t\talert(\"잘못된 타입입니다.\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tsel = document.querySelector(\"#type\" + questionIdx);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor (let i = 0; i < sel.length; i++) {\n");
      out.write("\t\t\t\tif (sel[i].value == type) {\n");
      out.write("\t\t\t\t\tsel[i].selected = true;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tquestionNumbering();\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction questionNumbering(){\n");
      out.write("\t\t\tfor(let i = 0; i < indexArray.length; i++) {\n");
      out.write("\t\t\t\tlet q = document.getElementById('question_num' + indexArray[i]);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tq.innerHTML = i + 1;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction making_index(){\n");
      out.write("\t\t\tconst form = document.getElementById('form');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor(let i = 0; i < indexArray.length; i++){\n");
      out.write("\t\t\t\tlet index = document.createElement(\"input\");\n");
      out.write("\t\t\t    index.type = \"hidden\";\n");
      out.write("\t\t\t    index.name = \"index\" + i;\n");
      out.write("\t\t\t    index.value = indexArray[i];\n");
      out.write("\n");
      out.write("\t\t\t    form.appendChild(index);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction formSubmit() {\n");
      out.write("\t\t\toverClick();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tconst form = document.getElementById('form');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tform.num_of_index.value = indexArray.length;\n");
      out.write("\n");
      out.write("\t\t\tmaking_index();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tform.submit();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction multiple(q_idx) {\n");
      out.write("\t\t\tvar multiple = \"<div class='multiple' id='multiple\" + q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<select id='type\" + q_idx + \"' name='type\" + q_idx + \"' onchange='changeType(\" + q_idx + \")'>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='multiple'>객관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='shortanswer'>주관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='matrix'>행렬형</option>\"\n");
      out.write("\t\t\t\t\t+ \"</select>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class='main_question_table' id='question\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='question_number'>Q<span id='question_num\" + q_idx + \"'></span></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class = 'question_title'><input type='text' class='question_title' placeholder='질문을 입력하세요.' name='main_question_title\" + q_idx + \"'></td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class = 'option_table' id='option\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='blank'>O</td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='option'><input type='text' class='option_content' placeholder='항목' name='option\" + q_idx + \"_0'></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='create_delete_option'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_option' onClick='addOption(\" + q_idx + \")' value='+'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_option' onClick='removeOption(\" + q_idx + \")' value='-'>\"\n");
      out.write("\t\t\t\t\t+ \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='multi_res\" + q_idx + \"'>중복 응답</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='multi_res\" + q_idx + \"' id='multi_res\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='necessary\" + q_idx + \"'>필수 응답</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='necessary\" + q_idx + \"' id='necessary\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='shuffle\" + q_idx + \"'>무작위</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='shuffle\" + q_idx + \"' id='shuffle\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' id='questionIndex' value='\"+ q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' name='option_count\" + q_idx + \"' id='option_count\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='btn' value='질문 제거' onclick='removeQuestion()'>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\treturn multiple;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction shortanswer(q_idx) {\n");
      out.write("\t\t\tvar shortanswer = \"<div class='shortanswer' id='shortanswer\" + q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<select id='type\" + q_idx + \"' name='type\" + q_idx + \"' onchange='changeType(\" + q_idx + \")'>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='multiple'>객관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='shortanswer'>주관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='matrix'>행렬형</option>\"\n");
      out.write("\t\t\t\t\t+ \"</select>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class='question_table' id='question\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='question_number'>Q<span id='question_num\" + q_idx + \"'></span></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class = 'question_title'><input type='text' class='question_title' placeholder='질문을 입력하세요.' name='main_question_title\" + q_idx + \"'></td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='necessary\" + q_idx + \"'>필수 응답</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='necessary\" + q_idx + \"' id='necessary\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' id='questionIndex' value='\"+ q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='btn' value='질문 제거' onclick='removeQuestion()'>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\";\n");
      out.write("\n");
      out.write("\t\t\treturn shortanswer;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction matrix(q_idx) {\n");
      out.write("\t\t\tvar matrix = \"<div class='matrix' id='matrix\" + q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<select id='type\" + q_idx + \"' name='type\" + q_idx + \"' onchange='changeType(\" + q_idx + \")'>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='multiple'>객관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='shortanswer'>주관식</option>\"\n");
      out.write("\t\t\t\t\t+ \"<option value='matrix'>행렬형</option>\"\n");
      out.write("\t\t\t\t\t+ \"</select>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class = 'title_question_table' id='main_question_title\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='question_number'>Q<span id='question_num\" + q_idx + \"'></span></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class = 'question_title'><input type='text' class='question_title' placeholder='대표 질문을 입력하세요.' name='main_question_title\" + q_idx + \"'></td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class = 'question_table' id='question\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='question_number'></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class = 'question_title'><input type='text' class='question_title' placeholder='질문을 입력하세요.' name='question_title\" + q_idx + \"_0'></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='create_delete_question'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_question' onClick='addMatrixQuestion(\" + q_idx + \")' value='+'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_question' onClick='removeMatrixQuestion(\" + q_idx + \")' value='-'>\"\n");
      out.write("\t\t\t\t\t+ \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t\t\t+ \"<table class = 'option_table' id='option\" + q_idx + \"' border='0' cellspacing='0' cellpadding='0'>\"\n");
      out.write("\t\t\t\t\t+ \"<tr>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='blank'>O</td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='option'><input type='text' class='option_content' placeholder='항목' name='option\" + q_idx + \"_0'></td>\"\n");
      out.write("\t\t\t\t\t+ \"<td class='create_delete_option'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_option' onClick='addOption(\" + q_idx + \")' value='+'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='create_delete_option' onClick='removeOption(\" + q_idx + \")' value='-'>\"\n");
      out.write("\t\t\t\t\t+ \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\"\n");
      out.write("\t\t\t\t\t+ \"</table>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='multi_res\" + q_idx + \"'>중복 응답</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='multi_res\" + q_idx + \"' id='multi_res\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='necessary\" + q_idx + \"'>필수 응답</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='necessary\" + q_idx + \"' id='necessary\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<label for='shuffle\" + q_idx + \"'>무작위</label>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='checkbox' name='shuffle\" + q_idx + \"' id='shuffle\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' id='questionIndex' value='\"+ q_idx + \"'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' name='question_count\" + q_idx + \"' id='question_count\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' name='option_count\" + q_idx + \"' id='option_count\" + q_idx + \"' value='1'>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='button' class='btn' value='질문 제거' onclick='removeQuestion()'>\"\n");
      out.write("\t\t\t\t\t+ \"</div>\";\n");
      out.write("\n");
      out.write("\t\t\treturn matrix;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction overClick() {\n");
      out.write("\t\t     if (click) {\n");
      out.write("\t\t          console.log(\"클릭됨\");\n");
      out.write("\t\t          click = !click;\n");
      out.write("\t\t     } else {\n");
      out.write("\t\t          console.log(\"중복됨\");\n");
      out.write("\t\t     }\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
