/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2021-04-28 11:43:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mileage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; utf-8;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>마일리지</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t<span id=\"bookmark\">즐겨찾기 추가</span><span id=\"top_menu\"><span\r\n");
      out.write("\t\t\tclass=\"top_menu_d\" onclick=\"location.href='index.jsp';\">홈</span><span\r\n");
      out.write("\t\t\tclass=\"top_menu_d\" onclick=\"location.href='LoginForm.jsp';\">로그인</span><span\r\n");
      out.write("\t\t\tclass=\"top_menu_d\" onclick=\"location.href='join.jsp';\">회원가입</span><span\r\n");
      out.write("\t\t\tclass=\"top_menu_d\">사이트맵</span></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"lmd\">\r\n");
      out.write("\t\t<img id=\"logoimg\" src=\"img/logo.png\"\r\n");
      out.write("\t\t\tonclick=\"location.href='index.jsp';\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"topmenu\">\r\n");
      out.write("\t\t<div id=\"topmenuwrap\">\r\n");
      out.write("\t\t\t<div id=\"topmenu1\">폴인사이트소개</div>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("          -->\r\n");
      out.write("\t\t\t<div id=\"topmenu2\">사업영역</div>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("          -->\r\n");
      out.write("\t\t\t<div id=\"topmenu3\">온라인조사</div>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("          -->\r\n");
      out.write("\t\t\t<div id=\"topmenu4\">커뮤니티</div>\r\n");
      out.write("\t\t\t<div id=\"submenuwrap\">\r\n");
      out.write("\t\t\t\t<div id=\"submenu\">\r\n");
      out.write("\t\t\t\t\t<div id=\"submenu1\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"subt1\" class=\"sub\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href='greeting.php';\">인사말</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sub\" onclick=\"location.href='history.php';\">연혁</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"submenu2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"subt2\" class=\"sub\" onclick=\"location.href='field.php';\">분야별영역</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sub\" onclick=\"location.href='performance1.php';\">주요실적</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"submenu3\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"subt3\" class=\"sub\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href='onlinesurvey.php';\">온라인설문</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sub\" onclick=\"location.href='polpointmall.php';\">포인트몰</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"submenu4\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"subt4\" class=\"sub\" onclick=\"location.href='notice.php';\">공지사항</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sub\" onclick=\"location.href='request.php';\">조사의뢰\r\n");
      out.write("\t\t\t\t\t\t\t및 문의</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"gtiwrap\">\r\n");
      out.write("\t\t<img id=\"gti\" src=\"img/gt.jpg\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"pagewrap\">\r\n");
      out.write("\t\t<div id=\"plm\">\r\n");
      out.write("\t\t\t<div id=\"gplmt\">&nbsp&nbsp&nbsp마이페이지</div>\r\n");
      out.write("\t\t\t<div id=\"gplmc1\" onclick=\"location.href='Account.jsp';\">&nbsp&nbsp&nbsp내정보관리</div>\r\n");
      out.write("\t\t\t<div id=\"gplmc2\" onclick=\"location.href='Mileage.jsp';\">&nbsp&nbsp&nbsp적립금관리</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--\r\n");
      out.write("        -->\r\n");
      out.write("\t\t<div id=\"pd\">\r\n");
      out.write("\t\t\t<div id=\"pdtt\">마이페이지</div>\r\n");
      out.write("\t\t\t<div id=\"pdtd\">적립금관리</div>\r\n");
      out.write("\t\t\t<div id=\"pd3\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t[62265] 광주광역시 광산구 첨단내촌로 70번길 55(월계동 769-4) 404호<br>T :\r\n");
      out.write("\t\t062-374-7011 F : 062-374-7013 E : polinsight@gmail.com<br>\r\n");
      out.write("\t\t<br>COPYRIGHT(C) 2019 POLINSIGHT. ALL RIGHTS RESERVED\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
